# Generated by Django 4.1.7 on 2023-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.FileField(upload_to='invoices/')),
                ('invoice_number', models.CharField(max_length=200)),
                ('client_number', models.CharField(max_length=200)),
                ('date_of_scanning', models.CharField(max_length=200)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
